#!/usr/bin/env bash
# Package xschem + CORE Tcl bridge into a portable tar.gz (RHEL 8 / Rocky 8).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INSTALL_PREFIX="${1:-$ROOT/dist-install}"
OUT_TAR="${2:-$ROOT/xschem-rocky8-bundle.tar.gz}"
BUNDLE_LABEL="${3:-Rocky Linux 8}"
XSCHEM_REPO="${XSCHEM_ROOT:-$ROOT}"
CAPNP_ROOT="${CAPNP_ROOT:-}"

BIN="$INSTALL_PREFIX/bin/xschem"
CORETCL="$XSCHEM_REPO/integrations/coretcl.so"
if [[ ! -x "$BIN" ]]; then
  echo "ERROR: xschem not found at $BIN (run build-xschem-ci.sh first)" >&2
  exit 1
fi
if [[ ! -f "$CORETCL" ]]; then
  echo "ERROR: coretcl.so not found at $CORETCL (run build-core-tcl.sh first)" >&2
  exit 1
fi

DIST="$ROOT/dist-bundle"
STAGE="$ROOT/.bundle-stage"
rm -rf "$DIST" "$STAGE"
mkdir -p "$DIST/bin" "$DIST/lib" "$DIST/share" "$DIST/integrations" "$STAGE/lib"

cp "$BIN" "$DIST/bin/xschem"
chmod +x "$DIST/bin/xschem"
cp -a "$CORETCL" "$DIST/integrations/coretcl.so"
cp -a "$XSCHEM_REPO/integrations/core.tcl" "$DIST/integrations/"
if [[ -d "$XSCHEM_REPO/integrations/qucs_symbols" ]]; then
  cp -a "$XSCHEM_REPO/integrations/qucs_symbols" "$DIST/integrations/"
fi
if [[ -d "$INSTALL_PREFIX/share" ]]; then
  cp -a "$INSTALL_PREFIX/share/." "$DIST/share/"
fi

bundle_skip_lib() {
  local base
  base="$(basename "$1")"
  case "$base" in
    ld-linux*|linux-vdso*|libc.so*|libm.so*|libpthread.so*|libdl.so*|librt.so*|libutil.so*|libresolv.so*|libnss_*|libgcc_s.so*|libstdc++.so*)
      return 0
      ;;
  esac
  return 1
}

bundle_copy_lib() {
  local lib="$1"
  [[ -n "$lib" && -f "$lib" ]] || return 0
  bundle_skip_lib "$lib" && return 0
  cp -Ln "$lib" "$STAGE/lib/" 2>/dev/null || cp -L "$lib" "$STAGE/lib/" || true
}

bundle_binary_libs() {
  local binary="$1"
  while IFS= read -r lib; do
    bundle_copy_lib "$lib"
  done < <(ldd "$binary" | awk '/=> \// {print $3}' | grep -v '^$' || true)
}

export LD_LIBRARY_PATH="${STAGE/lib}:${LD_LIBRARY_PATH:-}"
bundle_binary_libs "$BIN"
bundle_binary_libs "$CORETCL"

if [[ -n "$CAPNP_ROOT" && -d "$CAPNP_ROOT/lib" ]]; then
  cp -a "$CAPNP_ROOT/lib"/lib*.so* "$STAGE/lib/" 2>/dev/null || true
fi

if command -v patchelf >/dev/null 2>&1; then
  patchelf --set-rpath '$ORIGIN/../lib' "$DIST/bin/xschem" || true
  patchelf --set-rpath '$ORIGIN/../lib' "$DIST/integrations/coretcl.so" || true
fi

if [[ -d "$STAGE/lib" ]]; then
  cp -a "$STAGE/lib/." "$DIST/lib/" 2>/dev/null || true
fi

cat >"$DIST/xschemrc" <<'EOF'
# Portable Xschem + CORE bundle (generated by package_xschem_linux_bundle.sh)

set initial_geometry {1300x950}

set ::XSCHEM_ROOT [file normalize [file dirname [info script]]]

if {[info exists ::env(COMMONDB_ROOT)] && $::env(COMMONDB_ROOT) ne ""} {
  set ::CORE_ROOT [file normalize $::env(COMMONDB_ROOT)]
} elseif {[info exists ::env(CORE_ROOT)] && $::env(CORE_ROOT) ne ""} {
  set ::CORE_ROOT [file normalize $::env(CORE_ROOT)]
} else {
  set ::CORE_ROOT [file normalize [file join $::XSCHEM_ROOT .. CommonDB]]
}

set ::core_payload_dir [file join $::CORE_ROOT designs xschem payload]

set XSCHEM_LIBRARY_PATH {}
append XSCHEM_LIBRARY_PATH :$::core_payload_dir
append XSCHEM_LIBRARY_PATH :[file join $::XSCHEM_ROOT integrations qucs_symbols]
append XSCHEM_LIBRARY_PATH :[file join $::XSCHEM_ROOT share xschem xschem_library devices]
append XSCHEM_LIBRARY_PATH :[file join $::XSCHEM_ROOT share doc xschem examples]

set netlist_dir $::core_payload_dir

source [file join $::XSCHEM_ROOT integrations core.tcl]
EOF

cat >"$DIST/xschem-run.sh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"
export LD_LIBRARY_PATH="$DIR/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export XSCHEM_ROOT="$DIR"
export XSCHEM_RC="$DIR/xschemrc"
exec "$DIR/bin/xschem" --rcfile "$XSCHEM_RC" "$@"
EOF
chmod +x "$DIST/xschem-run.sh"

cat >"$DIST/BUNDLE.txt" <<EOF
Xschem + CORE portable bundle ($BUNDLE_LABEL)
Built: $(date -u +%Y-%m-%dT%H:%M:%SZ)

Run: ./xschem-run.sh

Requires: Linux x86_64 with glibc 2.28+ (RHEL 8 / Rocky Linux 8 / AlmaLinux 8).
Set COMMONDB_ROOT to your CommonDB checkout for CORE design payloads.
EOF

rm -rf "$STAGE"
tar -C "$ROOT" -czf "$OUT_TAR" "$(basename "$DIST")"
echo "Created $OUT_TAR"
